on:
  push:
    branches:
      - release

jobs:
  diff_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: list_changed
        name: List changed
        run: |
          
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"

          changed=()

          for dir in webs/* ; do
            if [ -d "$dir" ]; then
            
              echo "Found folder: $dir"

              if git diff --quiet "$BEFORE" "$AFTER" -- "$dir"; then
                echo "$dir has NO changes"
              else
                echo "$dir has changes"
                changed+=("${dir}")
              fi

            fi
          done

          echo "Changed packages: ${changed[*]}"

          echo "changed=$changed[@]" >> $GITHUB_OUTPUT

      - name: Use changed
        run: |

          echo "Changed JSON: ${{ steps.list_changed.outputs.changed }}"