on:
  push:
    branches:
      - release

jobs:
  diff_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show changed
        run: |
          echo "Before commit: ${{ github.event.before }}"
          echo "After commit: ${{ github.sha }}"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: List all top-level folders in current commit
        run: |
          
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"

          for dir in webs/* ; do
            if [ -d "$dir" ]; then
            
              echo "Found folder: $dir"

              if git diff --quiet "$BEFORE" "$AFTER" -- "$dir"; then
                echo "$dir has NO changes"
              else
                echo "$dir has changes"
              fi

            fi
          done