on:
  push:
    branches:
      - release

jobs:
  diff_check:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: list_changed
        name: List changed
        run: |
          
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"

          changed=()

          for dir in webs/* ; do
            if [ -d "$dir" ]; then
            
              echo "Found folder: $dir"

              if git diff --quiet "$BEFORE" "$AFTER" -- "$dir"; then
                echo "$dir has NO changes"
              else
                echo "$dir has changes"
                changed+=("${dir}")
              fi

            fi
          done

          echo "Changed packages: ${changed[*]}"

          if [ ${#changed[@]} -eq 0 ]; then
            echo "has_changed=false" >> $GITHUB_OUTPUT
          else
            echo "has_changed=true" >> $GITHUB_OUTPUT
          fi

          json=$(printf '%s\n' "${changed[@]}" | jq -R . | jq -s . | jq -c .)
          echo "list=$json" >> $GITHUB_OUTPUT

      - name: Use changed
        if: ${{ steps.check_changed.outputs.has_changed == 'true' }}
        run: |
          changed_packages=($(echo '${{ steps.list_changed.outputs.list }}' | jq -r '.[]'))

          if [ ${#changed_packages[@]} -eq 0 ]; then
            echo "数组为空"
          else
            for project in "${changed_packages[@]}"; do
              echo "Build $project"
              cd "$project"
            done
          fi