on:
  push:
    branches:
      - release

jobs:
  diff_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List all top-level folders in current commit
        run: |
          
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"

          changed=()

          for dir in webs/* ; do
            if [ -d "$dir" ]; then
            
              echo "Found folder: $dir"

              if git diff --quiet "$BEFORE" "$AFTER" -- "$dir"; then

              else
                changed+=("${dir}")
              fi

            fi
          done

          echo "Changed packages: ${changed[*]}