on:
  push:
    branches:
      - release

jobs:
  diff_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show changed
        run: |
          echo "Before commit: ${{ github.event.before }}"
          echo "After commit: ${{ github.sha }}"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: List all top-level folders in current commit
        run: |
          for dir in webs/* ; do
            if [ -d "$dir" ]; then
              echo "Found folder: $dir"
            fi
          done