on:
  push

jobs:
  diff_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show changed files
        run: |
          echo "Before commit: ${{ github.event.before }}"
          echo "After commit: ${{ github.sha }}"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}