on:
  push:
    branches:
      - release

jobs:
  diff_check:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: list_changed
        name: List changed
        run: |
          
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"

          changed=()

          for dir in webs/* ; do
            if [ -d "$dir" ]; then
            
              echo "Found folder: $dir"

              if git diff --quiet "$BEFORE" "$AFTER" -- "$dir"; then
                echo "$dir has NO changes"
              else
                echo "$dir has changes"
                changed+=("${dir}")
              fi

            fi
          done

          echo "Changed packages: ${changed[*]}"

          if [ ${#changed[@]} -eq 0 ]; then
            echo "has_changed=false" >> $GITHUB_OUTPUT
          else
            json=$(printf '%s\n' "${changed[@]}" | jq -R . | jq -s . | jq -c .)
            echo "list=$json" >> $GITHUB_OUTPUT
            echo "has_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        if: ${{ steps.list_changed.outputs.has_changed == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Use changed
        if: ${{ steps.list_changed.outputs.has_changed == 'true' }}
        run: |

          npm install -g pnpm
          pnpm --version

          changed_packages=($(echo '${{ steps.list_changed.outputs.list }}' | jq -r '.[]'))

          for project in "${changed_packages[@]}"; do
            echo "Build $project"
            cd "$project"
            pnpm install
            ls
          done